sudo: required
language: php
dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3
#  - 7.4

addons:
  chrome: stable

matrix:
  fast_finish: true

services:
  - mysql

install:
#  - wget - https://dl.google.com/dl/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo apt-get clean
  - sudo apt-get update
  - sudo apt-get install dpkg -f
#  - sudo apt-get -f install
#  - sudo apt upgrade dpkg
  - sudo dpkg -i /tmp/google-chrome-stable_current_amd64.deb
  - mysql -e 'create database if not exists laravel;'
  - composer self-update --2
  - travis_retry composer create-project --prefer-dist laravel/laravel laravel-tests
  - cp -f ./tests/resources/stubs/artisan ./laravel-tests/
  - cp -f ./tests/resources/stubs/ComposerConfigCommand.php ./laravel-tests/app/
  - mkdir ./laravel-tests/dcat-admin
  - cp -rf ./config ./laravel-tests/dcat-admin
  - cp -rf ./database ./laravel-tests/dcat-admin
  - cp -rf ./resources ./laravel-tests/dcat-admin
  - cp -rf ./src ./laravel-tests/dcat-admin
  - cp -rf ./tests ./laravel-tests/dcat-admin
  - cp -rf ./composer.json ./laravel-tests/dcat-admin
  - rm -rf ./laravel-tests/tests
  - cp -rf ./tests ./laravel-tests/tests
  - cp -f ./phpunit.dusk.xml ./laravel-tests
  - cp -f ./.env.testing ./laravel-tests/.env
  - cd ./laravel-tests
  - php artisan admin:composer-config
  - travis_retry composer require dcat/laravel-admin:*@dev
  - travis_retry composer require laravel/dusk --dev # --ignore-platform-reqs
#  - travis_retry composer require --dev staudenmeir/dusk-updater:"^1.1"
  - php artisan admin:publish --force
  - php artisan admin:install
  - php artisan migrate:rollback
  - php artisan dusk:chrome-driver 87
#  - php artisan dusk:update 79
  - cp -f ./tests/routes.php ./app/Admin/
  - cp -rf ./tests/resources/config ./config/

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - chmod 777 ./vendor/laravel/dusk/bin/chromedriver-linux
  - ./vendor/laravel/dusk/bin/chromedriver-linux --headless --disable-gpu --remote-debugging-port=9515 http://localhost &
  - php artisan serve &

script:
  - php artisan dusk

